version: 0.2
phases:
  pre_build:
    commands:
      - echo Forro solution Restore started on `date`
      - dotnet restore
      - echo Installing Amazon.Lambda.Tools, so it is possible to build it
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - echo  Forro solution Build started on `date`
      - dotnet lambda package -pl Forro.Lambda
      - echo Running CloudFormation Package command to generate the SAM output template
      - aws cloudformation package --template-file forrolambda-sam-template.yaml --s3-bucket paulo-bucket-deploy --output-template-file output-forrolambda-sam-template.yaml

artifacts:
  files:
    - forrolambda-sam-template.yaml
    - output-forrolambda-sam-template.yaml