version: 0.2
phases:
  pre_build:
    commands:
      - echo Forro solution Restore started on `date`
      - dotnet restore
      - echo Installing Amazon.Lambda.Tools, so it is possible to build it
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - echo  Forro solution Build started on `date`
      - dotnet lambda package -pl Forro.Lambda
artifacts:
  files:
    - Forro.Lambda/bin/Release/netcoreapp2.1/Forro.Lambda.zip